language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - cp monkey-patch/caporal/index.d.ts node_modules/caporal/index.d.ts

script:
  - npm run lint
  - npm run compile
  - npm run generate-config-schema
  - npm run build
