language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run lint
  - npm run compile
  - npm run generate-config-schema
  - npm run build
