language: node_js

node_js:
- '8'

cache:
  directories:
  - node_modules
  - ~/.nexe

env:
  global:
    - secure: "VY7YwITZ9+XeKkt4gO4L5abzzPsnMntoxzNrkDE/OdE3CXujpa/3MutArWuS2BZVPr9mu745gF8Ur4UsJZn0h5c9mhD/6fvFlLKQ6YG9g/YT8PNgQzpMC72TRJubds5cGRlSSy7u+3C5zkr1nsFnprOMjStrkiJNMvsRAdUlt1o/98rRj8Pyd01kizyO6SegrK/dYZhAZpVUjy3QnOuMZXVx8kmHZFekYnkxuM6rMZckAph1VjhJw3B7l3mzeBdqMtxBLUdwTK+NxyqNHc2exw/AjxtzLZfkm0tq7bxfEr7VE1P3CJLLMsIXjyb1s3XVnwjsb7AA/p0T0wXO9+AMvEK27Cnq6zzb5PpsHBfkJrPAjgPIdc9rhN+V3sFJxlHq3Uc1b1bS7UWlBwCQp9QWyp5m1HC+0Ah2CiuBzHV3ejv1ozLQ/uS3SpRMWKYyuu4PrVqERqsS6fexfrgu5JHYR070vErTfYGwIizbj4DFVpyvj2ZrSBlEl0NZ7E9Su31zTxx1c9S/U9NqjEVmVvDNUwL+aAdPquwmwGhrSqxJoTNeezcdzhl7FZxlm0l1gdi+9zFfhV14c6xqslFHv07AKQ0DnONcapdJesEZwqXyXu3Um7PEN+MrZMOKcfIo7aXt7DHSJzzhjcnACOP8Wq7yj/XTgcTYTBuw+F6Q2cKDjfo="

install:
- npm install
- cp monkey-patch/caporal/index.d.ts node_modules/caporal/index.d.ts

script:
- npm run lint
- npm run compile
- mkdir -p dist/schema
- npm run generate-config-schema
- npm run build
- ls -lah dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: QHcqnaKLSFTnypFU2Rr6mQznuEUN9nv/QSwewjHLARVsome5eiaebR4vjjk0N5l11gDOM579CTcp4HHHl7ChKD9hGRvNvBLc79rA9elQtYJ4/SZAp/E7Ibbo8WLb3f9tfkvqbKgK7Ee78vhP1VdcUxvw5XTPEBnkBOxiCUoLx0xTu94zcO1kLGBGtCuTKpThr0vLuBlL9c5z/3IBmZJPjc+ujEgUShiCN8IvFLomUuJvBPi9fjPIQ+dLvla45QXE3VSZ/tEbGT4xiFOzKvOCcL2YiFMBhwc03wiB0CbCepYvoamTLVBfqvutPL8X7g8gTR+xAsWbRD/BoATG9k3cdIICyVJ7ts+b+Z6TtXHcIMrkf7/3yM8tTFzvtO5UESb2dqpvkkk1X3qgUVPkHvjDF4wEKdet8npiLONldV+OxgVN9XR9k5PQWm3FQzzZaJtnsqLjgrHi4qu2orm1mNDECKTJsb3CQJlBomGcMFcKJMWrIp1BWIUu1gEED2QsZtsyBn5RrIseh3sTM4nqoKCMM95vNWx00Whfz7cHy8bo7CcvhY5ko4SXwCJszDP90RWbSuJdGmmE1dn5SDJrP4i4WyFzgaPmyJysyLC0afZquzES9kMPN3pkiSMNVORT7ey7T9cBCThxcEed9V7q6/CuwzBDcNI2n8QbGtwnMF6Y67M=
  file: dist/restic-orchestrator
  on:
    repo: datenknoten/restic-orchestrator
    tags: true
