language: node_js

node_js:
- '8'
- '7'

cache:
  directories:
  - node_modules
  - dist

env:
  global:
    - secure: "kdDR9t0ro61s3SR0MCqGoEMIqWQd2P4UGw/6sZz44hC5ZrvrdEiKcXKVgizaT6ZTBj92tIqFYPKF4iSoiXyPasvlb4wXabfaVzTGrM4/1V4If+oJNq/82vQD88Zw5htXqSSvNSNhrkUGPKCxSDbkzKdiaD1qg6xtRyeenOr7E9m1saMlJ382Es0BxAuUrqV1BF3FvUtjXyfIaPZXiC33yTQ5GSlZl+mb1+mjHWAaPBGq/8p4qTe1HBMxcxId79nzXIK0Pey+brWaSxkaKb1wMtQGO88vlf9TPovHgVQ3R803RIBl/TENWy66PYXv9B7TND5N1UcZlFeNsp164JHhMdLK+2jV1zMDWRbp91rQOWBGymd9cUGOk5UonRVBCMzhIaUuZUVKtAZ+JRAISLejT7ChnZtmY2f1aF7Sg8PuQj+W3VP6Ept6xnMkyLPH/VVlLiGy/D1pOwVudrEynTUHkzPDepS27Whf4hFhURFNkEPUQOD2ONKfdbCRxj2ac0jHg3o9MPlx+pzCE2Gji2scTg/fcGDmjkknf45zMD1DeyuaE7raQOFtVat6s/B8zhSA/epPETAU4n3P8y7bcbZsxVCgUcHIK4BZX4hS4j6isF0rESTrgex2vs3OhyapId1tua/xjWzlZJAcckWKrJLJwGkbw9zV4UuITIl2woVxRmY="
    - secure: "EPpUcGG2lMtqsc1oYeedPUd8tf5agq5EpfKg/hTa/xdl1jMGQMvF9TLQffrhBQR+qYRQBIwlNUK9D6v0excfuI2cRC1opLdAUa7UMgu1xhTV+zz2Guabiw11sForTFeF1JcKDlePsCMd1AcfxILqyw1glYRd/psqUdI39f7RaVKxaqRiI7STzyzq8HwEYC5U2CzuxHxClBZixMWyrROjw83QvX9D9/lHDzmXgzbr2Sik+98U66qVDLPpwbeyfnFiP2Ds9c4jdaMh1MAgjsNzucnEuWZwHq6sAjjVzH6THO4+UPmKSzQ0LXbPfNo+pFIoIsC8M56AkUvoi/sm9bd1Q247L3auR2sXJ752+TasKCyhPbDvSExGnW/NHH+vMECWjYZgP4wMTyvvzMGvgvKcL5yXkSr74J8mrMNjCVp0Kp867lxZ1/pcZGFYbcu/sM0HuOH/+TIc4uQTgRPyvjlSzKRcWzkSh/xXUy9Uyv2V8NZgsZhqvX1YpPSLX5myU5uBCV7/kfV0mrBsLHYfU2gm+li15sTdqsadoL7g0l/gh1vccxdc1PKorBOCjMQIOss++GyNTN/LXZ4JrRmKmwgLuqXPoB866BM9905DHGBTFHN35UTL6M1F2zxztLZy34LKlh2+jo8jN78mvl7///Zr+C9HMTXtZXsUbkPbn4IcAxs="

stages:
  - install
  - test
  - coverage
  - name: build
    if: tag IS present

jobs:
  include:
    - stage: install
      script:
        - npm install
        - cp monkey-patch/caporal/index.d.ts node_modules/caporal/index.d.ts
    - stage: test
      script:
        - npm run lint
        - npm run test
        - npm run compile
        - mkdir -p dist/schema
        - npm run generate-config-schema
    - stage: coverage
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - npm run coverage
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: build
      script:
        - sudo apt-get -qq update
        - sudo apt-get install -y upx-ucl
        - npm install --global modclean nexe
        - npm prune --production
        - modclean --run
        - npm run build
        - chmod u+x ~/.nexe/*
        - strip -s ~/.nexe/*
        - upx -9 ~/.nexe/*
        - npm run build
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: QHcqnaKLSFTnypFU2Rr6mQznuEUN9nv/QSwewjHLARVsome5eiaebR4vjjk0N5l11gDOM579CTcp4HHHl7ChKD9hGRvNvBLc79rA9elQtYJ4/SZAp/E7Ibbo8WLb3f9tfkvqbKgK7Ee78vhP1VdcUxvw5XTPEBnkBOxiCUoLx0xTu94zcO1kLGBGtCuTKpThr0vLuBlL9c5z/3IBmZJPjc+ujEgUShiCN8IvFLomUuJvBPi9fjPIQ+dLvla45QXE3VSZ/tEbGT4xiFOzKvOCcL2YiFMBhwc03wiB0CbCepYvoamTLVBfqvutPL8X7g8gTR+xAsWbRD/BoATG9k3cdIICyVJ7ts+b+Z6TtXHcIMrkf7/3yM8tTFzvtO5UESb2dqpvkkk1X3qgUVPkHvjDF4wEKdet8npiLONldV+OxgVN9XR9k5PQWm3FQzzZaJtnsqLjgrHi4qu2orm1mNDECKTJsb3CQJlBomGcMFcKJMWrIp1BWIUu1gEED2QsZtsyBn5RrIseh3sTM4nqoKCMM95vNWx00Whfz7cHy8bo7CcvhY5ko4SXwCJszDP90RWbSuJdGmmE1dn5SDJrP4i4WyFzgaPmyJysyLC0afZquzES9kMPN3pkiSMNVORT7ey7T9cBCThxcEed9V7q6/CuwzBDcNI2n8QbGtwnMF6Y67M=
        file: dist/restic-orchestrator
        on:
          tags: true


notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MDB4QUZGRSUzQW1hdHJpeC5vcmcvJTIxaWtsaVpGWGd0a1dWVW1FUmRQJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never