language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- npm install
- cp monkey-patch/caporal/index.d.ts node_modules/caporal/index.d.ts
script:
- npm run lint
- npm run compile
- mkdir -p dist/schema
- npm run generate-config-schema
- npm run build

deploy:
  provider: releases
  api_key:
    secure: QHcqnaKLSFTnypFU2Rr6mQznuEUN9nv/QSwewjHLARVsome5eiaebR4vjjk0N5l11gDOM579CTcp4HHHl7ChKD9hGRvNvBLc79rA9elQtYJ4/SZAp/E7Ibbo8WLb3f9tfkvqbKgK7Ee78vhP1VdcUxvw5XTPEBnkBOxiCUoLx0xTu94zcO1kLGBGtCuTKpThr0vLuBlL9c5z/3IBmZJPjc+ujEgUShiCN8IvFLomUuJvBPi9fjPIQ+dLvla45QXE3VSZ/tEbGT4xiFOzKvOCcL2YiFMBhwc03wiB0CbCepYvoamTLVBfqvutPL8X7g8gTR+xAsWbRD/BoATG9k3cdIICyVJ7ts+b+Z6TtXHcIMrkf7/3yM8tTFzvtO5UESb2dqpvkkk1X3qgUVPkHvjDF4wEKdet8npiLONldV+OxgVN9XR9k5PQWm3FQzzZaJtnsqLjgrHi4qu2orm1mNDECKTJsb3CQJlBomGcMFcKJMWrIp1BWIUu1gEED2QsZtsyBn5RrIseh3sTM4nqoKCMM95vNWx00Whfz7cHy8bo7CcvhY5ko4SXwCJszDP90RWbSuJdGmmE1dn5SDJrP4i4WyFzgaPmyJysyLC0afZquzES9kMPN3pkiSMNVORT7ey7T9cBCThxcEed9V7q6/CuwzBDcNI2n8QbGtwnMF6Y67M=
  file: dist/restic-orchestrator
  on:
    repo: datenknoten/restic-orchestrator
    tags: true
